################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
# copyright
copyright = "muleML"

# <a target="_blank" rel="noopener noreferrer" href="">

################################### Italian language #####################################
[it]
languageName = "It"
languageCode = "it-it"
contentDir = "content/italian"
weight = 2

[it.params]
# copyright
copyright = "muleML"

################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3

[fr.params]
# copyright
home = "Accueil"
copyright = "muleML"
