
# Aggiunge le intestazioni per impedire indicizzazione motori di ricerca
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet, noimageindex"

# Attiva l'Edge Function su tutto il sito
[[edge_functions]]
path = "/*"
function = "basic-auth"

# Impostazioni che servono per la preview
[context.deploy-preview.environment]
  HUGO_BASEURL = "/"

[context.branch-deploy.environment]
  HUGO_BASEURL = "/"

#Evitare sia sempre attivo muleml.netlify.app
[[redirects]]
  from = "/*"
  to = "https://www.muleml.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["muleml.netlify.app"] }
