backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pages-en"
    label: "Pages (English)"
    folder: "content/english"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}/"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "pages-fr"
    label: "Pages (Francais)"
    folder: "content/french"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }


  - name: "blog-en"
    label: "Blog (English)"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "blog-fr"
    label: "Blog (Francais)"
    folder: "content/french/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }
