backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:

  - name: "authors-en"
    label: "Authors (English)"
    folder: "content/english/author"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    preview_path: "author/{{slug}}/"

    fields:
      - { label: "Name", name: "title", widget: "string" }

      - label: "Photo (optional)"
        name: "image"
        widget: "string"
        required: false
        hint: "Inserisci solo il nome file (es. 02.jpg) presente in assets/images/avatars/"
        pattern: "^(?:|[A-Za-z0-9._-]+\\.(?:jpg|jpeg|png|webp|gif))$"
        
        
      # Social: 
      - label: "Social links"
        name: "social"
        widget: "list"
        collapsed: true
        summary: "{{fields.name}} → {{fields.link}}"
        fields:
          - { label: "Icon (class)", name: "icon", widget: "string", hint: "Esempio: fab fa-linkedin-in" }
          - { label: "Name", name: "name", widget: "select", options: ["linkedin", "facebook", "twitter", "x", "instagram", "github", "website"] }
          - { label: "Link (URL)", name: "link", widget: "string" }

      - { label: "Bio", name: "body", widget: "markdown", hint: "Breve descrizione/bio dell'autore" }

  - name: "blog-en"
    label: "Blog (English)"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}/"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Cover Image", name: "image", widget: "image", choose_url: false }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }


  - name: "blog-fr"
    label: "Blog (Français)"
    folder: "content/french/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}/"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Image de couverture", name: "image", widget: "image", choose_url: true }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

