backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pages-en"
    label: "Pages (English)"
    folder: "content/english"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}/"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "pages-fr"
    label: "Pages (Francais)"
    folder: "content/french"
    create: true
    slug: "{{slug}}"
    preview_path: "fr/{{slug}}/"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }



  - name: "blog-en"
    label: "Blog (English)"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Cover Image", name: "image", widget: "image", choose_url: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }


  - name: "blog-fr"
    label: "Blog (Français)"
    folder: "content/french/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Image de couverture", name: "image", widget: "image", choose_url: true }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

